const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Follow,
		C3.Plugins.Touch,
		C3.Behaviors.EightDir,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.progressbar,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{FundoMenu: 0},
	{Logo: 0},
	{Seguir: 0},
	{Sprite: 0},
	{btn_touche: 0},
	{btn_play: 0},
	{cansprint: 0},
	{sprinttime: 0},
	{sprintspeedmult: 0},
	{sprintcooldown: 0},
	{"8Direções": 0},
	{ProjetorDeSombra: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{str_person_paradoo: 0},
	{PlanoDeFundoEmBlocos: 0},
	{state: 0},
	{Projétil: 0},
	{str_lataLixo: 0},
	{Texto: 0},
	{Teclado: 0},
	{str_arvore: 0},
	{str_ruaReta: 0},
	{str_ruaretaInfinita: 0},
	{Âncora: 0},
	{str_barra_progresso: 0},
	{str_grama: 0},
	{str_terra_2: 0},
	{FundoBlocos_Terra2: 0},
	{fundoBloco_gramaBoa: 0},
	{str_gramaBoa: 0},
	{Sólido: 0},
	{str_casa: 0},
	{str_casa_gpt01: 0},
	{str_estradaReta: 0},
	{str_estradaReta2: 0},
	{Pontos: 0}
];

self.InstanceType = {
	FundoMenu: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	btn_touche: class extends self.IInstance {},
	btn_play: class extends self.ISpriteInstance {},
	str_person_paradoo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	str_lataLixo: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	str_arvore: class extends self.ISpriteInstance {},
	str_ruaReta: class extends self.ISpriteInstance {},
	str_ruaretaInfinita: class extends self.ITiledBackgroundInstance {},
	str_barra_progresso: class extends self.IProgressBarInstance {},
	str_grama: class extends self.ITiledBackgroundInstance {},
	str_terra_2: class extends self.ISpriteInstance {},
	FundoBlocos_Terra2: class extends self.ITiledBackgroundInstance {},
	fundoBloco_gramaBoa: class extends self.ITiledBackgroundInstance {},
	str_gramaBoa: class extends self.ISpriteInstance {},
	str_casa: class extends self.ISpriteInstance {},
	str_casa_gpt01: class extends self.ISpriteInstance {},
	str_estradaReta: class extends self.ISpriteInstance {},
	str_estradaReta2: class extends self.ISpriteInstance {}
}